### ISSUE TITLE
Doesn't work in ESM environments

### ISSUE THREAD

**Issue by anselmbradford** [saucelabs/sauce-playwright-runner#202]
This package doesn't run in environments configured for EcmaScript Modules, because of the `require` calls in:
https://github.com/saucelabs/sauce-playwright-runner/blob/main/src/sauce.config.js#L1-L3

Running this from GitHub Actions I get:

```
Sauce Playwright Runner 2.17.0
Running Playwright 1.31.1
Preparing npm environment
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'D:\sauce-playwright-runner\2.17.0\bundle\__project__\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///D:/sauce-playwright-runner/2.17.0/bundle/__project__/sauce.config.js:1:17
```

Can `sauce.config.js` be renamed to `sauce.config.cjs`, or can the requires be updated to be imports?

**Comment by alexplischke** [comment]
May I ask about your usecase? Our runners weren't made with the intent to be used directly (or as a library/sdk).

The idea is that you can use playwright as-is locally to develop and run your tests. Or in your CI. And if you need a flexible way to run against browsers on different operating systems or versions, you can use saucectl to launch those tests on the Sauce Labs platform, where this runner here will perform the task of running the tests as scheduled by saucectl.

There should be no need to use this runner inside your CI or dev environment.

Alternatively, if all you are trying to do is report your test results from playwright to Sauce Labs, you can [use our reporter instead](https://github.com/saucelabs/sauce-playwright-reporter).

**Comment by alexplischke** [comment]
Ah gotcha! I'll have our team look at this 🙏

**Comment by mhan83** [comment]
@anselmbradford I believe this is fixed in the latest release candidate (https://github.com/saucelabs/sauce-playwright-runner/releases/tag/v2.17.1-rc.1.0)

It'll be another week or so before the latest version of the runner is generally available. If you want to try this release before its availability, you can use the `--runner-version` flag to specify a runner to use by url. e.g.

`saucectl run --runner-version "url: https://github.com/saucelabs/sauce-playwright-runner/releases/download/v2.17.1-rc.1.0/playwright-{macos|windows}-amd64.zip"`

The release asset is platform specific, so ensure you're using the correct zip for the platform you're testing against.

Also, keep in mind that running tests with a custom runner is significantly slower since additional time will be required to download and extract the archive. It's not recommended for regular use.
